/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangundatar_202557201013;

/**
 *
 * @author LENOVO
 */
public class AplikasiBangunDatar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AplikasiBangunDatar.class.getName());

    /**
     * Creates new form AplikasiBangunDatar
     */
    public AplikasiBangunDatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSegiTiga = new javax.swing.JButton();
        btnPersegiPanjang = new javax.swing.JButton();
        btnLingkaran = new javax.swing.JButton();
        btnPersegi = new javax.swing.JButton();
        btnSegiLima = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSegiEnam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Menghitung Luas Dan Keliling Bangun Datar");

        btnSegiTiga.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnSegiTiga.setText("Segi Tiga");
        btnSegiTiga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSegiTiga.addActionListener(this::btnSegiTigaActionPerformed);

        btnPersegiPanjang.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnPersegiPanjang.setText("Persegi Panjang");
        btnPersegiPanjang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersegiPanjang.addActionListener(this::btnPersegiPanjangActionPerformed);

        btnLingkaran.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnLingkaran.setText("Lingkaran");
        btnLingkaran.addActionListener(this::btnLingkaranActionPerformed);

        btnPersegi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnPersegi.setText("Persegi");
        btnPersegi.addActionListener(this::btnPersegiActionPerformed);

        btnSegiLima.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnSegiLima.setText("Segi Lima");
        btnSegiLima.addActionListener(this::btnSegiLimaActionPerformed);

        btnExit.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        btnSegiEnam.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnSegiEnam.setText("Segi Enam");
        btnSegiEnam.addActionListener(this::btnSegiEnamActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSegiEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSegiLima, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersegiPanjang)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnExit)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnSegiTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(132, 132, 132)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSegiTiga)
                .addGap(18, 18, 18)
                .addComponent(btnPersegiPanjang)
                .addGap(18, 18, 18)
                .addComponent(btnLingkaran)
                .addGap(18, 18, 18)
                .addComponent(btnPersegi)
                .addGap(18, 18, 18)
                .addComponent(btnSegiLima)
                .addGap(18, 18, 18)
                .addComponent(btnSegiEnam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSegiTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegiTigaActionPerformed
        // TODO add your handling code here:
         new FrameSegiTiga().setVisible(true);
    }//GEN-LAST:event_btnSegiTigaActionPerformed

    private void btnPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersegiPanjangActionPerformed
        // TODO add your handling code here:
        new FramePersegiPanjang().setVisible(true);
    }//GEN-LAST:event_btnPersegiPanjangActionPerformed

    private void btnLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLingkaranActionPerformed
        // TODO add your handling code here:
         new FrameLingkaran().setVisible(true);
    }//GEN-LAST:event_btnLingkaranActionPerformed

    private void btnPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersegiActionPerformed
        // TODO add your handling code here:
         new FramePersegi().setVisible(true);
    }//GEN-LAST:event_btnPersegiActionPerformed

    private void btnSegiLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegiLimaActionPerformed
        // TODO add your handling code here:
         new FrameSegiLima().setVisible(true);
    }//GEN-LAST:event_btnSegiLimaActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSegiEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegiEnamActionPerformed
        // TODO add your handling code here:
        new FrameSegiEnam().setVisible(true);
    }//GEN-LAST:event_btnSegiEnamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AplikasiBangunDatar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLingkaran;
    private javax.swing.JButton btnPersegi;
    private javax.swing.JButton btnPersegiPanjang;
    private javax.swing.JButton btnSegiEnam;
    private javax.swing.JButton btnSegiLima;
    private javax.swing.JButton btnSegiTiga;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
