/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangundatar202557201013;

/**
 *
 * @author LENOVO
 */
public class bangundatar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bangundatar.class.getName());

    /**
     * Creates new form bangundatar
     */
    public bangundatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnsegitiga = new javax.swing.JButton();
        btnPersegiPanjang = new javax.swing.JButton();
        btnlingkaran = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnPersegi = new javax.swing.JButton();
        btnSegiLima = new javax.swing.JButton();
        btnSegiEnam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Bangun Datar");

        btnsegitiga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsegitiga.setText("Segitiga");
        btnsegitiga.addActionListener(this::btnsegitigaActionPerformed);

        btnPersegiPanjang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPersegiPanjang.setText("Persegi Panjang");
        btnPersegiPanjang.addActionListener(this::btnPersegiPanjangActionPerformed);

        btnlingkaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlingkaran.setText("Lingkaran");
        btnlingkaran.addActionListener(this::btnlingkaranActionPerformed);

        btnExit.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        btnPersegi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPersegi.setText("Persegi");
        btnPersegi.addActionListener(this::btnPersegiActionPerformed);

        btnSegiLima.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSegiLima.setText("Segi Lima");
        btnSegiLima.addActionListener(this::btnSegiLimaActionPerformed);

        btnSegiEnam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSegiEnam.setText("Segi Enam");
        btnSegiEnam.addActionListener(this::btnSegiEnamActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPersegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPersegiPanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSegiLima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnlingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(btnSegiEnam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersegiPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSegiLima, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSegiEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsegitigaActionPerformed
        // TODO add your handling code here:
        new Framesegitiga().setVisible(true);
    }//GEN-LAST:event_btnsegitigaActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersegiPanjangActionPerformed
        // TODO add your handling code here:
        new FramePersegiPanjang().setVisible(true);
    }//GEN-LAST:event_btnPersegiPanjangActionPerformed

    private void btnlingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlingkaranActionPerformed
        // TODO add your handling code here:
        new FrameLingkaran().setVisible(true);
    }//GEN-LAST:event_btnlingkaranActionPerformed

    private void btnPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersegiActionPerformed
        // TODO add your handling code here:
        new FramePersegi().setVisible(true);
    }//GEN-LAST:event_btnPersegiActionPerformed

    private void btnSegiLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegiLimaActionPerformed
        // TODO add your handling code here:
        new FrameSegiLima().setVisible(true);
    }//GEN-LAST:event_btnSegiLimaActionPerformed

    private void btnSegiEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegiEnamActionPerformed
        // TODO add your handling code here:
        new FrameSegiEnam().setVisible(true);
    }//GEN-LAST:event_btnSegiEnamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bangundatar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPersegi;
    private javax.swing.JButton btnPersegiPanjang;
    private javax.swing.JButton btnSegiEnam;
    private javax.swing.JButton btnSegiLima;
    private javax.swing.JButton btnlingkaran;
    private javax.swing.JButton btnsegitiga;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
